#!/bin/bash
# Hook: SessionStart — staleデータの自動修復
# freshness-check.sh の結果に基づき、修復可能なものを自動実行
# async: true
#
# 自動修復対象:
# - CEO分析 (7日超): prompt_logからSupabase ceo_insightsへINSERT
# - 情報収集 (1日超): GitHub Actions dispatch (要設定)
# - 部署評価は手動（AI判断が必要なため freshness-alert.sh で指示）

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
source "$SCRIPT_DIR/supabase-check.sh" 2>/dev/null || true
[ "${SUPABASE_AVAILABLE:-false}" = "true" ] || exit 0

RESULT=$(bash "$SCRIPT_DIR/freshness-check.sh" 2>/dev/null) || exit 0
[ -z "$RESULT" ] && exit 0

NOW_EPOCH=$(date +%s)

# === CEO分析の自動実行 ===
CEO_DATE=$(echo "$RESULT" | jq -r '.sources.ceo_insights.last_updated // "never"' 2>/dev/null)
CEO_STALE=false
if [ "$CEO_DATE" = "never" ] || [ "$CEO_DATE" = "null" ]; then
  CEO_STALE=true
else
  CEO_EPOCH=$(date -d "$CEO_DATE" +%s 2>/dev/null || echo 0)
  [ $((NOW_EPOCH - CEO_EPOCH)) -gt 604800 ] && CEO_STALE=true  # 7日 = 604800秒
fi

if [ "$CEO_STALE" = "true" ]; then
  # prompt_logから直近のパターンを集計してceo_insightsに保存
  # 時間帯分布を分析
  HOUR_DIST=$(curl -4 -s "${SUPABASE_URL}/rest/v1/rpc/exec_sql" \
    -H "apikey: ${SUPABASE_ANON_KEY}" \
    -H "Authorization: Bearer ${SUPABASE_ANON_KEY}" \
    -H "x-ingest-key: ${SUPABASE_INGEST_KEY}" \
    -H "Content-Type: application/json" \
    -d '{"query":"SELECT extract(hour from created_at at time zone '\''Asia/Tokyo'\'') as hour, count(*) as cnt FROM prompt_log GROUP BY hour ORDER BY cnt DESC LIMIT 3"}' \
    --connect-timeout 5 --max-time 10 2>/dev/null || echo "[]")

  # 曜日分布
  DOW_DIST=$(curl -4 -s "${SUPABASE_URL}/rest/v1/rpc/exec_sql" \
    -H "apikey: ${SUPABASE_ANON_KEY}" \
    -H "Authorization: Bearer ${SUPABASE_ANON_KEY}" \
    -H "x-ingest-key: ${SUPABASE_INGEST_KEY}" \
    -H "Content-Type: application/json" \
    -d '{"query":"SELECT extract(dow from created_at at time zone '\''Asia/Tokyo'\'') as dow, count(*) as cnt FROM prompt_log GROUP BY dow ORDER BY cnt DESC LIMIT 3"}' \
    --connect-timeout 5 --max-time 10 2>/dev/null || echo "[]")

  # 直近30日のプロンプト数
  RECENT_COUNT=$(curl -4 -s "${SUPABASE_URL}/rest/v1/prompt_log?select=id&created_at=gt.$(date -d '30 days ago' +%Y-%m-%dT00:00:00Z 2>/dev/null || echo '2026-03-01T00:00:00Z')" \
    -H "apikey: ${SUPABASE_ANON_KEY}" \
    -H "Authorization: Bearer ${SUPABASE_ANON_KEY}" \
    -H "x-ingest-key: ${SUPABASE_INGEST_KEY}" \
    -H "Prefer: count=exact" \
    -H "Range: 0-0" \
    -I --connect-timeout 5 --max-time 10 2>/dev/null | grep -i 'content-range' | sed 's/.*\///' | tr -d '[:space:]' || echo "?")

  # ceo_insightsにINSERT
  INSIGHT="直近30日のプロンプト数: ${RECENT_COUNT}件。ピーク時間帯: ${HOUR_DIST}。曜日分布: ${DOW_DIST}。"
  curl -4 -s -o /dev/null \
    "${SUPABASE_URL}/rest/v1/ceo_insights" \
    -H "apikey: ${SUPABASE_ANON_KEY}" \
    -H "Authorization: Bearer ${SUPABASE_ANON_KEY}" \
    -H "x-ingest-key: ${SUPABASE_INGEST_KEY}" \
    -H "Content-Type: application/json" \
    -H "Prefer: return=minimal" \
    -d "{\"category\":\"work_rhythm\",\"insight\":\"${INSIGHT}\",\"evidence\":\"auto-generated by freshness-auto-fix.sh\",\"confidence\":\"medium\"}" \
    --connect-timeout 5 --max-time 10 2>/dev/null || true
fi

exit 0
